version: '3.3'

services:
  aerztekasse-api:
    #build: .
    image: zoltansco/aerztekasse:aerztekasse-api-2025.04.02
    container_name: aerztekasse-api
    restart: always
    ports:
      - "8300:8080"
    expose:
      - '8300'
    depends_on:
      - aerztekasse-api-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://aerztekasse-api-mysql:3306/aerztekasse
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - aerztekasse-net

  aerztekasse-api-mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: aerztekasse-api-mysql
    environment:
      MYSQL_DATABASE: 'aerztekasse'
      MYSQL_USER: 'aerztekasse'
      MYSQL_PASSWORD: 'aerztekasse'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - aerztekasse-api-mysql-db:/var/lib/mysql
    networks:
      - aerztekasse-net

volumes:
  aerztekasse-api-mysql-db:

networks:
  aerztekasse-net:
    driver: bridge
