version: '3.3'

services:
  ui:
    image: zoltansco/aerztekasse:aerztekasse-app-2025.3.30
    container_name: aerztekasse-app
    restart: always
    ports:
      - 8301:8080
    expose:
      - 8301
    depends_on:
      - aerztekasse-app
    networks:
      - aerztekasse-net

  aerztekasse-api:
    build: docker-local
    container_name: aerztekasse-api
    restart: always
    ports:
      - "8300:8080"
    expose:
      - '8300'
    depends_on:
      - aerztekasse-mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://aerztekasse-mysql-db:3306/aerztekasse?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - aerztekasse-net

  aerztekasse-mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: aerztekasse-mysql-db
    environment:
      MYSQL_DATABASE: 'aerztekasse'
      MYSQL_USER: 'aerztekasse'
      MYSQL_PASSWORD: 'aerztekasse'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - aerztekasse-mysql-volume:/var/lib/mysql
    networks:
      - aerztekasse-net

volumes:
  aerztekasse-mysql-volume:

networks:
  aerztekasse-net:
    driver: bridge
