version: '3.3'

services:
  aerztekasse-mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: aerztekasse-mysql-db
    environment:
      MYSQL_DATABASE: 'aerztekasse'
      MYSQL_USER: 'aerztekasse'
      MYSQL_PASSWORD: 'aerztekasse'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - aerztekasse-mysql-volume:/var/lib/mysql
volumes:
  aerztekasse-mysql-volume:
